In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
train_df=pd.read_csv("C:/Users/Lenovo/Desktop/digikala/1/data/train.csv")
test_df=pd.read_csv("C:/Users/Lenovo/Desktop/digikala/1/data/test.csv")

In [3]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68840 entries, 0 to 68839
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   id                   68840 non-null  int64 
 1   product_description  68840 non-null  object
 2   price                68840 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 1.6+ MB


In [4]:
train_df.isnull().sum()

id                     0
product_description    0
price                  0
dtype: int64

In [5]:
train_df.head()

id                                product_description    price
0   0  {'مشخصات فنی': 'متراژ: 150 سانتی متر\r\nپورت ی...  1080000
1   1  {'مشخصات فنی': 'CABLE LENTH:\r\n10feet \\/3M\r...   990000
2   2  {'مشخصات فنی': 'نوع کابل: KVM USB\r\nطول کابل:...  1680000
3   3       {'دسته بندی': 'کابل کمبو', 'برند': 'متفرقه'}  4500000
4   4  {'مشخصات فنی': 'کیبورد: 6pin Mini-DIN Male - P...   700000

In [6]:
train_df.set_index("id",inplace=True)

In [7]:
train_df_x= train_df.drop("price",axis=1)
train_df_y=train_df["price"]
train_df_y=train_df_y.to_frame(name="price")

In [8]:
train_df_x.head()

product_description
id                                                   
0   {'مشخصات فنی': 'متراژ: 150 سانتی متر\r\nپورت ی...
1   {'مشخصات فنی': 'CABLE LENTH:\r\n10feet \\/3M\r...
2   {'مشخصات فنی': 'نوع کابل: KVM USB\r\nطول کابل:...
3        {'دسته بندی': 'کابل کمبو', 'برند': 'متفرقه'}
4   {'مشخصات فنی': 'کیبورد: 6pin Mini-DIN Male - P...

In [9]:
train_df_y.head()

price
id         
0   1080000
1    990000
2   1680000
3   4500000
4    700000

In [10]:
train_df_x["product_description"]

id
0        {'مشخصات فنی': 'متراژ: 150 سانتی متر\r\nپورت ی...
1        {'مشخصات فنی': 'CABLE LENTH:\r\n10feet \\/3M\r...
2        {'مشخصات فنی': 'نوع کابل: KVM USB\r\nطول کابل:...
3             {'دسته بندی': 'کابل کمبو', 'برند': 'متفرقه'}
4        {'مشخصات فنی': 'کیبورد: 6pin Mini-DIN Male - P...
                               ...                        
68835    {'دسته بندی': 'شارژر تبلت و موبایل', 'برند': '...
68836    {'دسته بندی': 'شارژر تبلت و موبایل', 'برند': '...
68837    {'دسته بندی': 'شارژر تبلت و موبایل', 'برند': '...
68838    {'کابل همراه': ['لایتنینگ'], 'ولتاژ خروجی': ['...
68839    {'وزن': 'یک سانتی\u200cمتر', 'درگاه\u200cهای ا...
Name: product_description, Length: 68840, dtype: object

In [11]:
pd.set_option("max_colwidth", None)
train_df_x["product_description"].to_frame().head()

product_description
id                                                                                                                                                                                                                                                                                                               
0                                                                                                                                                                                                             {'مشخصات فنی': 'متراژ: 150 سانتی متر\r\nپورت یو اس بی', 'دسته بندی': 'کابل کمبو', 'برند': 'متفرقه'}
1   {'مشخصات فنی': 'CABLE LENTH:\r\n10feet \\/3M\r\nPC SIDE CONNECTORS_CONNECTED TO PC : \r\nPS\\/2 Keyboard mini-Din 6 pin, male\r\nPS\\/2 Mouse Mini-Din 6 pin, male\r\nVGA HDDB 15pin, male\r\nKVM SIDE CONNECTORS-CONNECTED TO KVM SWITCH: \r\nHDDB 15pin, male', 'دسته بندی': 'کابل کمبو', 'برند': 'ادیمکس'}
2                                                                                                                                                                                                            {'مشخصات فنی': 'نوع کابل: KVM USB\r\nطول کابل: 1.5 متر', 'دسته بندی': 'کابل کمبو', 'برند': 'متفرقه'}
3                                                                                                                                                                                                                                                                    {'دسته بندی': 'کابل کمبو', 'برند': 'متفرقه'}
4                                                                                                         {'مشخصات فنی': 'کیبورد: 6pin Mini-DIN Male - Purple \r\nموس: 6pin Mini-DIN Male - Green\r\nمانیتور: 15pin HD DB type Male - Blue\r\nمتراژ: 300 سانتی متر', 'دسته بندی': 'کابل کمبو', 'برند': 'دی-لینک'}

In [12]:
train_df_x["product_description"] = train_df_x["product_description"].apply(lambda x : dict(eval(x)) )
df3 = train_df_x["product_description"].apply(pd.Series )

In [13]:
df3.columns

Index(['مشخصات فنی', 'دسته بندی', 'برند', 'کارکرد', 'دستگاه‌های سازگار',
       'سایر توضیحات', 'حجم', 'ابعاد', 'وزن', 'قابلیت‌های گام‌شمار',
       ...
       'عمر باتری محفظه شارژ', 'منبع تغذیه هدفون', 'امکانات ارتباطی',
       'منبع تغذیه فرستنده', 'سایر توضیحات کابل', 'بازه طول کابل',
       'نوع کانکتور', 'سایر توضیحات مبدل', 'پشتیبانی از', 'قابلیت‌های شارژر'],
      dtype='object', length=1480)

In [14]:
pd.set_option('display.max_columns', None)
df3.head()

مشخصات فنی  \
id                                                                                                                                                                                                                                                 
0                                                                                                                                                                                                          متراژ: 150 سانتی متر\r\nپورت یو اس بی   
1   CABLE LENTH:\r\n10feet \/3M\r\nPC SIDE CONNECTORS_CONNECTED TO PC : \r\nPS\/2 Keyboard mini-Din 6 pin, male\r\nPS\/2 Mouse Mini-Din 6 pin, male\r\nVGA HDDB 15pin, male\r\nKVM SIDE CONNECTORS-CONNECTED TO KVM SWITCH: \r\nHDDB 15pin, male   
2                                                                                                                                                                                                         نوع کابل: KVM USB\r\nطول کابل: 1.5 متر   
3                                                                                                                                                                                                                                            NaN   
4                                                                                                       کیبورد: 6pin Mini-DIN Male - Purple \r\nموس: 6pin Mini-DIN Male - Green\r\nمانیتور: 15pin HD DB type Male - Blue\r\nمتراژ: 300 سانتی متر   

    دسته بندی     برند کارکرد دستگاه‌های سازگار سایر توضیحات  حجم ابعاد  وزن  \
id                                                                             
0   کابل کمبو   متفرقه    NaN               NaN          NaN  NaN   NaN  NaN   
1   کابل کمبو   ادیمکس    NaN               NaN          NaN  NaN   NaN  NaN   
2   کابل کمبو   متفرقه    NaN               NaN          NaN  NaN   NaN  NaN   
3   کابل کمبو   متفرقه    NaN               NaN          NaN  NaN   NaN  NaN   
4   کابل کمبو  دی-لینک    NaN               NaN          NaN  NaN   NaN  NaN   

   قابلیت‌های گام‌شمار مشخصات باتری نرم افزار یا اپلیکیشن سازگار سایر امکانات  \
id                                                                              
0                  NaN          NaN                          NaN          NaN   
1                  NaN          NaN                          NaN          NaN   
2                  NaN          NaN                          NaN          NaN   
3                  NaN          NaN                          NaN          NaN   
4                  NaN          NaN                          NaN          NaN   

   درگاه‌های ارتباطی حافظه داخلی لوازم جانبی سیستم عامل اپلیکیشن حساسیت  \
id                                                                        
0                NaN         NaN         NaN                 NaN    NaN   
1                NaN         NaN         NaN                 NaN    NaN   
2                NaN         NaN         NaN                 NaN    NaN   
3                NaN         NaN         NaN                 NaN    NaN   
4                NaN         NaN         NaN                 NaN    NaN   

   جنس بدنه ولتاژ ورودی درجه چرخش جنس صندلی تعداد نمایشگر قابل نصب  \
id                                                                   
0       NaN         NaN       NaN       NaN                    NaN   
1       NaN         NaN       NaN       NaN                    NaN   
2       NaN         NaN       NaN       NaN                    NaN   
3       NaN         NaN       NaN       NaN                    NaN   
4       NaN         NaN       NaN       NaN                    NaN   

   ابعاد هر نمایشگر مدل سیستم صوتی امکانات کنترلی قابلیت‌ها امکانات جانبی  \
id                                                                          
0               NaN            NaN            NaN       NaN           NaN   
1               NaN            NaN            NaN       NaN           NaN   
2               NaN            NaN            NaN       NaN        

In [15]:
df3.shape

(68840, 1480)

In [16]:
nan_cols=df3.columns[df3.isnull().sum()>60000]

In [17]:
nan_cols

Index(['مشخصات فنی', 'کارکرد', 'دستگاه‌های سازگار', 'سایر توضیحات', 'حجم',
       'قابلیت‌های گام‌شمار', 'مشخصات باتری', 'نرم افزار یا اپلیکیشن سازگار',
       'سایر امکانات', 'حافظه داخلی',
       ...
       'عمر باتری محفظه شارژ', 'منبع تغذیه هدفون', 'امکانات ارتباطی',
       'منبع تغذیه فرستنده', 'سایر توضیحات کابل', 'بازه طول کابل',
       'نوع کانکتور', 'سایر توضیحات مبدل', 'پشتیبانی از', 'قابلیت‌های شارژر'],
      dtype='object', length=1473)

In [18]:
nan_columns=df3.isnull().sum()/df3.shape[0]

In [19]:
nan_cols=df3.columns[nan_columns>.5]

In [20]:
nan_cols

Index(['مشخصات فنی', 'کارکرد', 'دستگاه‌های سازگار', 'سایر توضیحات', 'حجم',
       'ابعاد', 'قابلیت‌های گام‌شمار', 'مشخصات باتری',
       'نرم افزار یا اپلیکیشن سازگار', 'سایر امکانات',
       ...
       'عمر باتری محفظه شارژ', 'منبع تغذیه هدفون', 'امکانات ارتباطی',
       'منبع تغذیه فرستنده', 'سایر توضیحات کابل', 'بازه طول کابل',
       'نوع کانکتور', 'سایر توضیحات مبدل', 'پشتیبانی از', 'قابلیت‌های شارژر'],
      dtype='object', length=1477)

In [21]:
df3.columns.size

1480

In [22]:
## so as you can see there are just 4 columns(1480-1476) that have null values less than 60000

In [23]:
df3.drop(nan_cols,axis=1,inplace=True)

In [24]:
df3.columns

Index(['دسته بندی', 'برند', 'وزن'], dtype='object')

In [25]:
df3.isnull().sum()

دسته بندی        0
برند             0
وزن          31156
dtype: int64

In [26]:
result_x = pd.concat([train_df_x, df3], axis=1).drop('product_description', axis=1)

In [27]:
result_x.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 68840 entries, 0 to 68839
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   دسته بندی  68840 non-null  object
 1   برند       68840 non-null  object
 2   وزن        37684 non-null  object
dtypes: object(3)
memory usage: 2.1+ MB


In [28]:
result_x["دسته بندی"].value_counts()

شارژر تبلت و موبایل       4380
کابل و مبدل               4327
هدفون، هدست و هندزفری     4148
محافظ لنز گوشی موبایل     4114
فلش مموری                 2754
                          ... 
ریسوگراف                     9
لوازم جانبی NAS و سرور       9
گیت وی                       9
کاغذ چاپ سریع                9
کابل کمبو                    6
Name: دسته بندی, Length: 180, dtype: int64

In [29]:
result_x["برند"].value_counts()

متفرقه                33127
هورس                   1332
باسئوس                  946
لنوو                    721
ماهوت                   623
                      ...  
آی بی ام                  1
ایسر پریدیتور             1
ایکس وی ایکس              1
فرست بلاد انلی گیم        1
ورسون                     1
Name: برند, Length: 1658, dtype: int64

In [30]:
result_x["وزن"].value_counts()

ضد خش             1610
تی‌شرت و شلوار    1580
رومی              1559
بند قابل تعویض    1496
یک سانتی‌متر      1354
                  ... 
آمریکا               1
 با باتری 385        1
1.167                1
0.731                1
130                  1
Name: وزن, Length: 1826, dtype: int64

In [31]:
## وزن columns has lots of irrelevant values so we drop in from result_x

In [32]:
result_x.drop("وزن" , axis=1,inplace=True)

In [33]:
result_x.head(10)

دسته بندی     برند
id                    
0   کابل کمبو   متفرقه
1   کابل کمبو   ادیمکس
2   کابل کمبو   متفرقه
3   کابل کمبو   متفرقه
4   کابل کمبو  دی-لینک
5   کابل کمبو   متفرقه
6    ریسوگراف   متفرقه
7    ریسوگراف   متفرقه
8    ریسوگراف   متفرقه
9    ریسوگراف   متفرقه

In [34]:
result_x["برند"].isnull().sum()

0

In [35]:
result_x["دسته بندی"].isnull().sum()

0

In [36]:
from sklearn.preprocessing import LabelEncoder

In [37]:
label_encoder = LabelEncoder()
berand = label_encoder.fit_transform(result_x["برند"])

np.save('classes.npy', label_encoder.classes_)
berand

array([1033,   99, 1033, ..., 1062,  734, 1152])

In [38]:
##np.set_printoptions(threshold=np.inf)
berand

array([1033,   99, 1033, ..., 1062,  734, 1152])

In [39]:
dastebandi = label_encoder.fit_transform(result_x["دسته بندی"])
## np.save('classes.npy', label_encoder.classes_)
dastebandi

array([151, 151, 151, ...,  71,  71,  71])

In [40]:
result_x.apply(LabelEncoder().fit_transform)


دسته بندی  برند
id                    
0            151  1033
1            151    99
2            151  1033
3            151  1033
4            151   656
...          ...   ...
68835         71  1075
68836         71   156
68837         71  1062
68838         71   734
68839         71  1152

[68840 rows x 2 columns]

In [41]:
label_encoder.transform(result_x["دسته بندی"].to_frame())

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([151, 151, 151, ...,  71,  71,  71])

In [42]:
result_x["دسته بندی"].value_counts()

شارژر تبلت و موبایل       4380
کابل و مبدل               4327
هدفون، هدست و هندزفری     4148
محافظ لنز گوشی موبایل     4114
فلش مموری                 2754
                          ... 
ریسوگراف                     9
لوازم جانبی NAS و سرور       9
گیت وی                       9
کاغذ چاپ سریع                9
کابل کمبو                    6
Name: دسته بندی, Length: 180, dtype: int64

In [43]:
a= result_x["دسته بندی"]

In [44]:
a

id
0                  کابل کمبو
1                  کابل کمبو
2                  کابل کمبو
3                  کابل کمبو
4                  کابل کمبو
                ...         
68835    شارژر تبلت و موبایل
68836    شارژر تبلت و موبایل
68837    شارژر تبلت و موبایل
68838    شارژر تبلت و موبایل
68839    شارژر تبلت و موبایل
Name: دسته بندی, Length: 68840, dtype: object

In [45]:
a[1]

'کابل کمبو'

In [46]:
a[3445]

'دستگاه کنترل تردد'

In [47]:
b= result_x["برند"]

In [48]:
b[2]

'متفرقه'

In [49]:
b[43]

'پاناسونیک'

In [50]:
berand

array([1033,   99, 1033, ..., 1062,  734, 1152])

In [51]:
dastebandi

array([151, 151, 151, ...,  71,  71,  71])

In [52]:
berand=pd.DataFrame(berand,columns=["berand"])

In [53]:
dastebandi=pd.DataFrame(dastebandi,columns=["dastebandi"])

In [54]:
##dastebandi

In [55]:
final_x_train= pd.concat([berand,dastebandi],axis=1)

In [56]:
#final_x_train

In [57]:
test_df.head()

id  \
0   0   
1   1   
2   2   
3   3   
4   4   

                                                                                                                                                                                                                                                                                                            product_description  
0                                                                                                               {'سازگار با': 'C21N1401\r\nX455', 'ولتاژ باتری': '7.6', 'ظرفیت باتری': 'کولا', 'مناسب برای لپ\u200cتاپ\u200cهای برند': ['Asus'], 'محل قرارگیری': ['داخلی'], 'دسته بندی': 'باتری لپ\u200cتاپ', 'برند': 'متفرقه'}  
1                                                                                                 {'سازگار با': 'A31N1519\r\nX540', 'ولتاژ باتری': '11.1', 'ظرفیت باتری': 'انبر سیم\u200cچین', 'مناسب برای لپ\u200cتاپ\u200cهای برند': ['Asus'], 'محل قرارگیری': ['داخلی'], 'دسته بندی': 'باتری لپ\u200cتاپ', 'برند': 'متفرقه'}  
2  {'تعداد فن': 'ندارد', 'نوع سیستم خنک کنندگی': 'ندارد', 'سایر توضیحات': 'قایلیت چرخش 360 درجه\r\nدارای جای مخصوص گوشی موبایل\r\nبدون فن', 'مناسب برای لپ تاپ های': ['تا 15.6 اینچی'], 'جنس بدنه': 'پلاستیک فشرده', 'ابعاد': '300x300x30', 'وزن': 'اکریلیک', 'دسته بندی': 'استند و پایه خنک\u200cکننده', 'برند': 'کیو وای اچ'}  
3                                                        {'سازگار با': 'A41N1424\r\nGL552\r\nZX50\r\nASUS ROG FX\r\nASUS ROG ZX50', 'ولتاژ باتری': '14.8', 'ظرفیت باتری': 'انبر سیم\u200cچین', 'مناسب برای لپ\u200cتاپ\u200cهای برند': ['Asus'], 'محل قرارگیری': ['خارجی'], 'دسته بندی': 'باتری لپ\u200cتاپ', 'برند': 'متفرقه'}  
4                                                                                                           {'سازگار با': 'AP31\r\nASUS 1008', 'ولتاژ باتری': '10.95', 'ظرفیت باتری': 'اسپرت', 'مناسب برای لپ\u200cتاپ\u200cهای برند': ['Asus'], 'محل قرارگیری': ['داخلی'], 'دسته بندی': 'باتری لپ\u200cتاپ', 'برند': 'متفرقه'}

In [58]:
test_df["product_description"] =test_df["product_description"].apply(lambda x : dict(eval(x)) )
df4 = test_df["product_description"].apply(pd.Series )

In [59]:
df4=df4[["برند","دسته بندی"]]

In [60]:
##label_encoder = LabelEncoder()

##label_encoder.classes_ = np.load('classes.npy',allow_pickle=True)

In [61]:
df4.apply(LabelEncoder().fit_transform)


برند  دسته بندی
0       819         17
1       819         17
2      1238          7
3       819         17
4       819         17
...     ...        ...
34257   300         71
34258   819         71
34259   576         71
34260   819         71
34261   639         71

[34262 rows x 2 columns]

In [62]:

#berand_test = label_encoder.fit_transform(df4["برند"])
#dastebandi_test = label_encoder.fit_transform(df4["دسته بندی"])

#berand_test=pd.DataFrame(berand_test,columns=["berand"])
#dastebandi_test=pd.DataFrame(dastebandi_test,columns=["dastebandi"])


In [63]:
# x_test = pd.concat([berand_test,dastebandi_test],axis=1)

In [64]:
df4=df4.apply(LabelEncoder().fit_transform)


In [65]:
final_x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68840 entries, 0 to 68839
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   berand      68840 non-null  int32
 1   dastebandi  68840 non-null  int32
dtypes: int32(2)
memory usage: 537.9 KB


In [66]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34262 entries, 0 to 34261
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   برند       34262 non-null  int32
 1   دسته بندی  34262 non-null  int32
dtypes: int32(2)
memory usage: 267.8 KB


In [67]:
train_df_y

price
id             
0       1080000
1        990000
2       1680000
3       4500000
4        700000
...         ...
68835   2530000
68836  22000000
68837   4000000
68838   4300000
68839    950000

[68840 rows x 1 columns]

In [68]:
df4.shape

(34262, 2)

In [69]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [70]:
## when we don't have x_test
## X_train, X_test, y_train, y_test = train_test_split(final_x_train , train_df_y , test_size=0.3, random_state=42)

In [71]:
model= LinearRegression()

In [72]:
model.fit(final_x_train ,train_df_y)

LinearRegression()

In [73]:
#X_train.shape ,y_train.shape

In [74]:
#X_test.shape ,y_test.shape

In [75]:
predict = model.predict(df4)

In [76]:
predict

array([[12921885.12245343],
       [12921885.12245343],
       [ 3220763.70081625],
       ...,
       [22119644.57915876],
       [16923191.82539915],
       [20772416.0874433 ]])

In [77]:
prediction=pd.DataFrame(predict, columns=["price"])

In [78]:
prediction

price
0      1.292189e+07
1      1.292189e+07
2      3.220764e+06
3      1.292189e+07
4      1.292189e+07
...             ...
34257  2.802179e+07
34258  1.692319e+07
34259  2.211964e+07
34260  1.692319e+07
34261  2.077242e+07

[34262 rows x 1 columns]

In [79]:
final_x_train.shape

(68840, 2)

In [80]:
prediction.shape

(34262, 1)

In [81]:
train_df_n=train_df.reset_index()

In [82]:
train_df_n

id  \
0          0   
1          1   
2          2   
3          3   
4          4   
...      ...   
68835  68835   
68836  68836   
68837  68837   
68838  68838   
68839  68839   

                                                                                                                                                                                                                                                                                                       product_description  \
0                                                                                                                                                                                                                      {'مشخصات فنی': 'متراژ: 150 سانتی متر\r\nپورت یو اس بی', 'دسته بندی': 'کابل کمبو', 'برند': 'متفرقه'}   
1            {'مشخصات فنی': 'CABLE LENTH:\r\n10feet \\/3M\r\nPC SIDE CONNECTORS_CONNECTED TO PC : \r\nPS\\/2 Keyboard mini-Din 6 pin, male\r\nPS\\/2 Mouse Mini-Din 6 pin, male\r\nVGA HDDB 15pin, male\r\nKVM SIDE CONNECTORS-CONNECTED TO KVM SWITCH: \r\nHDDB 15pin, male', 'دسته بندی': 'کابل کمبو', 'برند': 'ادیمکس'}   
2                                                                                                                                                                                                                     {'مشخصات فنی': 'نوع کابل: KVM USB\r\nطول کابل: 1.5 متر', 'دسته بندی': 'کابل کمبو', 'برند': 'متفرقه'}   
3                                                                                                                                                                                                                                                                             {'دسته بندی': 'کابل کمبو', 'برند': 'متفرقه'}   
4                                                                                                                  {'مشخصات فنی': 'کیبورد: 6pin Mini-DIN Male - Purple \r\nموس: 6pin Mini-DIN Male - Green\r\nمانیتور: 15pin HD DB type Male - Blue\r\nمتراژ: 300 سانتی متر', 'دسته بندی': 'کابل کمبو', 'برند': 'دی-لینک'}   
...                                                                                                                                                                                                                                                                                                                    ...   
68835                                                                                                                                                                                                                                                               {'دسته بندی': 'شارژر تبلت و موبایل', 'برند': 'موکسوم'}   
68836                                                                                                                                                                                                                                                                {'دسته بندی': 'شارژر تبلت و موبایل', 'برند': 'ال جی'}   
68837                                                                                                                                                                                                                                                                 {'دسته بندی': 'شارژر تبلت و موبایل', 'برند': 'مورف'}   
68838                                                                                                      {'کابل همراه': ['لایتنینگ'], 'ولتاژ خروجی': ['5.0 ولت'], 'شدت جریان خروجی': ['2.4 آمپر', '2.4 آمپر مخصوص تبلت و موبایل'], 'تعداد درگاه خروجی': ['دو عدد'], 'دسته بندی': 'شارژر تبلت و موبایل', 'برند': 'ریمکس'}   
68839  {'وزن': 'یک سانتی\u200cمتر', 'درگاه\u200cهای ارتباطی': ['Pin 2mm'], 'کابل همراه': ['Pin 2mm'], 'توضیحات': 'سازگار با تمام گوشی های نوکیا سوزنی\r\nاین شارژر با جریان خروجی 890 میلی آمپر گوشی های نوکیا را سریع شارژ میکند.', 'تعداد درگاه خروجی': ['یک عدد'], 'دسته بندی': 'شارژر تبلت و موبایل', 'برند': 'نوکیا'}   



In [92]:
prediction["id"]=train_df_n["id"]

In [93]:
prediction

price     id
id                        
0      1.292189e+07      0
1      1.292189e+07      1
2      3.220764e+06      2
3      1.292189e+07      3
4      1.292189e+07      4
...             ...    ...
34257  2.802179e+07  34257
34258  1.692319e+07  34258
34259  2.211964e+07  34259
34260  1.692319e+07  34260
34261  2.077242e+07  34261

[34262 rows x 2 columns]

In [94]:
prediction= prediction[["id","price"]]

In [95]:
prediction.set_index("id",inplace=True)

In [96]:
prediction

price
id                 
0      1.292189e+07
1      1.292189e+07
2      3.220764e+06
3      1.292189e+07
4      1.292189e+07
...             ...
34257  2.802179e+07
34258  1.692319e+07
34259  2.211964e+07
34260  1.692319e+07
34261  2.077242e+07

[34262 rows x 1 columns]

In [97]:
prediction.to_csv("output.csv")

In [88]:
#y_test["prediction"]=predict