In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("C:/Users/Lenovo/Desktop/digikala/3/purchase_history.csv",parse_dates=[2])

In [3]:
df.head()

user_id  product_id created_at
0    647746     2011564 2019-02-09
1    906136     4105782 2019-11-23
2  12862997     2144063 2019-07-16
3  12097079     1207738 2019-04-05
4   3184486     4278839 2019-03-08

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2174447 entries, 0 to 2174446
Data columns (total 3 columns):
 #   Column      Dtype         
---  ------      -----         
 0   user_id     int64         
 1   product_id  int64         
 2   created_at  datetime64[ns]
dtypes: datetime64[ns](1), int64(2)
memory usage: 49.8 MB


In [5]:
df.isnull().sum()

user_id       0
product_id    0
created_at    0
dtype: int64

In [6]:
df["user_id"].value_counts()

29623462    13604
38514908     4514
7024706      3434
3424777      3410
7359226      2431
            ...  
1030577         4
1165576         4
9539526         4
7052017         4
3233681         4
Name: user_id, Length: 96688, dtype: int64

In [7]:
features=["user_id","product_id","day","Month"]

In [8]:
target="created_at"

In [27]:
df['created_at']

0         2019-02-09
1         2019-11-23
2         2019-07-16
3         2019-04-05
4         2019-03-08
             ...    
2174442   2019-09-22
2174443   2019-07-15
2174444   2019-07-30
2174445   2019-02-09
2174446   2019-11-13
Name: created_at, Length: 2174447, dtype: datetime64[ns]

In [28]:
date_col= df['created_at'].astype(str).str.split('-', expand=True)

In [29]:
date_col.columns = ['Year', 'Month', 'Day']


In [30]:
date_col

Year Month Day
0        2019    02  09
1        2019    11  23
2        2019    07  16
3        2019    04  05
4        2019    03  08
...       ...   ...  ..
2174442  2019    09  22
2174443  2019    07  15
2174444  2019    07  30
2174445  2019    02  09
2174446  2019    11  13

[2174447 rows x 3 columns]

In [31]:
df1=pd.concat([df.drop("created_at",axis=1),date_col],axis=1)

In [32]:
df1

user_id  product_id  Year Month Day
0          647746     2011564  2019    02  09
1          906136     4105782  2019    11  23
2        12862997     2144063  2019    07  16
3        12097079     1207738  2019    04  05
4         3184486     4278839  2019    03  08
...           ...         ...   ...   ...  ..
2174442   2602547     1624033  2019    09  22
2174443  14188320      924263  2019    07  15
2174444   6774415      871217  2019    07  30
2174445  12176860     1604228  2019    02  09
2174446   1456614     1688713  2019    11  13

[2174447 rows x 5 columns]

In [33]:
df.drop("created_at",axis=1)

user_id  product_id
0          647746     2011564
1          906136     4105782
2        12862997     2144063
3        12097079     1207738
4         3184486     4278839
...           ...         ...
2174442   2602547     1624033
2174443  14188320      924263
2174444   6774415      871217
2174445  12176860     1604228
2174446   1456614     1688713

[2174447 rows x 2 columns]

In [34]:
df

user_id  product_id created_at
0          647746     2011564 2019-02-09
1          906136     4105782 2019-11-23
2        12862997     2144063 2019-07-16
3        12097079     1207738 2019-04-05
4         3184486     4278839 2019-03-08
...           ...         ...        ...
2174442   2602547     1624033 2019-09-22
2174443  14188320      924263 2019-07-15
2174444   6774415      871217 2019-07-30
2174445  12176860     1604228 2019-02-09
2174446   1456614     1688713 2019-11-13

[2174447 rows x 3 columns]

In [35]:
df1["Year"].value_counts()

2019    2174447
Name: Year, dtype: int64

In [36]:
df1["Day"].value_counts(dropna=False)

22    77921
11    77227
27    75997
28    75510
24    74509
26    74016
08    73617
14    73066
12    72713
23    72636
09    72571
04    72494
25    72484
07    72222
03    71721
18    71654
21    71625
15    71387
10    71265
13    69966
16    69134
02    68927
05    68729
17    68616
06    68384
01    66568
20    66181
29    65693
19    65668
30    60141
31    41805
Name: Day, dtype: int64

In [37]:
df1

user_id  product_id  Year Month Day
0          647746     2011564  2019    02  09
1          906136     4105782  2019    11  23
2        12862997     2144063  2019    07  16
3        12097079     1207738  2019    04  05
4         3184486     4278839  2019    03  08
...           ...         ...   ...   ...  ..
2174442   2602547     1624033  2019    09  22
2174443  14188320      924263  2019    07  15
2174444   6774415      871217  2019    07  30
2174445  12176860     1604228  2019    02  09
2174446   1456614     1688713  2019    11  13

[2174447 rows x 5 columns]

In [38]:
df

user_id  product_id created_at
0          647746     2011564 2019-02-09
1          906136     4105782 2019-11-23
2        12862997     2144063 2019-07-16
3        12097079     1207738 2019-04-05
4         3184486     4278839 2019-03-08
...           ...         ...        ...
2174442   2602547     1624033 2019-09-22
2174443  14188320      924263 2019-07-15
2174444   6774415      871217 2019-07-30
2174445  12176860     1604228 2019-02-09
2174446   1456614     1688713 2019-11-13

[2174447 rows x 3 columns]

In [39]:
# because all the years are same we don't need to use them for prediction
features=["user_id","product_id"]
target=["Day","Month"]

In [53]:
df1.shape

(2174447, 5)

In [40]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [54]:
X_train, X_test, y_train, y_test = train_test_split(df1[features], df1[target], test_size=0.15, random_state=42)

In [55]:
model = LinearRegression()

In [56]:
model.fit(X_train,y_train)

LinearRegression()

In [57]:
prediction= model.predict(X_test)

In [58]:
prediction

array([[15.80436711,  6.15882043],
       [15.65214246,  5.80416235],
       [15.8130217 ,  6.19502572],
       ...,
       [15.67298562,  5.83951934],
       [15.63282195,  5.73398121],
       [15.93561241,  6.497795  ]])

In [59]:
y_test

Day Month
1872703  25    07
798761   14    01
17499    05    04
254561   09    02
1627415  06    02
...      ..   ...
1430942  16    07
2091370  18    06
411312   24    05
1722643  17    07
1033028  30    05

[326168 rows x 2 columns]

In [60]:
prediction

array([[15.80436711,  6.15882043],
       [15.65214246,  5.80416235],
       [15.8130217 ,  6.19502572],
       ...,
       [15.67298562,  5.83951934],
       [15.63282195,  5.73398121],
       [15.93561241,  6.497795  ]])

In [61]:
prediction=np.round(prediction,decimals =0)

In [62]:
prediction

array([[16.,  6.],
       [16.,  6.],
       [16.,  6.],
       ...,
       [16.,  6.],
       [16.,  6.],
       [16.,  6.]])

In [63]:
pd.DataFrame(prediction)[1].value_counts()

6.0    255235
7.0     70575
8.0       358
Name: 1, dtype: int64

In [64]:
y_test

Day Month
1872703  25    07
798761   14    01
17499    05    04
254561   09    02
1627415  06    02
...      ..   ...
1430942  16    07
2091370  18    06
411312   24    05
1722643  17    07
1033028  30    05

[326168 rows x 2 columns]

In [65]:
prediction

array([[16.,  6.],
       [16.,  6.],
       [16.,  6.],
       ...,
       [16.,  6.],
       [16.,  6.],
       [16.,  6.]])

In [66]:
y_test["Day_pred"]=prediction[:,0]
y_test["month_pred"]=prediction[:,1]

In [67]:
y_test

Day Month  Day_pred  month_pred
1872703  25    07      16.0         6.0
798761   14    01      16.0         6.0
17499    05    04      16.0         6.0
254561   09    02      16.0         6.0
1627415  06    02      16.0         6.0
...      ..   ...       ...         ...
1430942  16    07      16.0         6.0
2091370  18    06      16.0         6.0
411312   24    05      16.0         6.0
1722643  17    07      16.0         6.0
1033028  30    05      16.0         6.0

[326168 rows x 4 columns]

In [74]:
prediction.shape

(326168, 2)

In [68]:
y_test["Day_pred"].value_counts()

16.0    326168
Name: Day_pred, dtype: int64

In [69]:
y_test["month_pred"].value_counts()

6.0    255235
7.0     70575
8.0       358
Name: month_pred, dtype: int64

In [70]:
prediction=pd.DataFrame(prediction,columns=["Day","Month"])

In [75]:
prediction_new=pd.concat([prediction,df1["Year"].head(326168)],axis=1)

In [76]:
prediction_new=prediction_new[["Year","Month","Day"]]

In [77]:
prediction_new

Year  Month   Day
0       2019    6.0  16.0
1       2019    6.0  16.0
2       2019    6.0  16.0
3       2019    6.0  16.0
4       2019    6.0  16.0
...      ...    ...   ...
326163  2019    6.0  16.0
326164  2019    6.0  16.0
326165  2019    6.0  16.0
326166  2019    6.0  16.0
326167  2019    6.0  16.0

[326168 rows x 3 columns]

In [79]:
#month = prediction_new["Month"].copy()
#prediction_new["Year"]= prediction_new["Year"].str.cat(month, sep ="-")
#prediction_new["Year"].str.cat(prediction_new["Month"], sep='-')

In [80]:
prediction_new.isnull().sum()

Year     0
Month    0
Day      0
dtype: int64

In [81]:
prediction_new[["Year"]]

Year
0       2019
1       2019
2       2019
3       2019
4       2019
...      ...
326163  2019
326164  2019
326165  2019
326166  2019
326167  2019

[326168 rows x 1 columns]

In [82]:
pd.Series(prediction_new["Month"])

0         6.0
1         6.0
2         6.0
3         6.0
4         6.0
         ... 
326163    6.0
326164    6.0
326165    6.0
326166    6.0
326167    6.0
Name: Month, Length: 326168, dtype: float64

In [83]:
prediction_new["Month"]

0         6.0
1         6.0
2         6.0
3         6.0
4         6.0
         ... 
326163    6.0
326164    6.0
326165    6.0
326166    6.0
326167    6.0
Name: Month, Length: 326168, dtype: float64

In [84]:
prediction_new

Year  Month   Day
0       2019    6.0  16.0
1       2019    6.0  16.0
2       2019    6.0  16.0
3       2019    6.0  16.0
4       2019    6.0  16.0
...      ...    ...   ...
326163  2019    6.0  16.0
326164  2019    6.0  16.0
326165  2019    6.0  16.0
326166  2019    6.0  16.0
326167  2019    6.0  16.0

[326168 rows x 3 columns]

In [85]:
prediction_new['Full Date'] = prediction_new['Year'].map(str) + '-' + prediction_new['Month'].map(str) + '-' + prediction_new['Day'].map(str)

In [86]:
prediction_new

Year  Month   Day      Full Date
0       2019    6.0  16.0  2019-6.0-16.0
1       2019    6.0  16.0  2019-6.0-16.0
2       2019    6.0  16.0  2019-6.0-16.0
3       2019    6.0  16.0  2019-6.0-16.0
4       2019    6.0  16.0  2019-6.0-16.0
...      ...    ...   ...            ...
326163  2019    6.0  16.0  2019-6.0-16.0
326164  2019    6.0  16.0  2019-6.0-16.0
326165  2019    6.0  16.0  2019-6.0-16.0
326166  2019    6.0  16.0  2019-6.0-16.0
326167  2019    6.0  16.0  2019-6.0-16.0

[326168 rows x 4 columns]

In [87]:
next_purchase=prediction_new['Full Date']

In [88]:
next_purchase=next_purchase.to_frame(name="next_purchase")


In [89]:
next_perchase=next_purchase.set_index("next_purchase")

In [90]:
next_perchase

Empty DataFrame
Columns: []
Index: [2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-7.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-8.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-7.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, ...]

[326168 rows x 0 columns]

In [91]:
next_perchase=next_perchase.head(318050)

In [92]:
next_perchase

Empty DataFrame
Columns: []
Index: [2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-7.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-8.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-7.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-7.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, 2019-6.0-16.0, ...]

[318050 rows x 0 columns]

In [93]:
next_perchase.shape

(318050, 0)

In [94]:
next_perchase.to_csv("answer.csv")